# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
nl:
 languageCode: nl
 contentDir: content/nl
 title: Sujin & Wouter's Bruiloft
 params:
   marketing:
    seo:
      description: 'Sujin & Wouter nodigen jullie uit voor hun bruiloft op zaterdag, 26 April, 2025 - 12h00 te Bucheon, Zuid-Korea.'
 menu:
   main:
    - name: Home
      url: '#top'
      weight: 10
    - name: Uitnodiging
      url: '#invitation'
      weight: 20
    - name: Details & tips
      url: '#tips'
      weight: 30
    - name: Gallery
      url: '#gallery'
      weight: 40
ko:
 languageCode: ko
 contentDir: content/ko
 title: "수진 워우터의 결혼식"
 params:
   marketing:
    seo:
      description: '저희 결혼식에 초대합니다. 2025년 04월 26일 토요일 오후 12시, 부천한옥체험마을에, 전통혼례입니다'
 menu:
   main:
     - name: 초대장
       url: '#top'
       weight: 10
     - name: 결혼 세부
       url: '#details'
       weight: 20
     - name: 전통혼례안내
       url: '#ceremony'
       weight: 20
     - name: 사진
       url: '#gallery'
       weight: 30