# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#top
    weight: 10
  - name: Wedding invitation
    url: /#invitation
    weight: 20
  - name: Details & tips
    url: /#tips
    weight: 30
  - name: Gallery
    url: /#gallery
    weight: 40
